### ISSUE TITLE
Bulk Sharing Tool Issue

### ISSUE THREAD

**Issue by alexwillingham98** [thoughtspot/cs_tools#65] opened 2023-07-19 15:52 UTC
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

Info snapshot taken on 2023-07-19                                                                        │
│                                                                                                                    │
│               CS Tools: 1.4.4                                                                                      │
│         Python Version: Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]    │
│            System Info: Windows (detail: Windows-10-10.0.19045-SP0)                                                │
│      Configs Directory: C:\Users\alexw\AppData\Roaming\cs_tools                                                    │
│    Activate VirtualEnv: C:\Users\alexw\AppData\Roaming\cs_tools\.cs_tools\Scripts\Activate.ps1                     │
│          Platform Tags: win-amd64

### Description

The Bulk Sharing tool doesn't seem to show permissions for a table with a lot of columns. I will do my best to provide a screenshot but can't show everything due to data privacy.
(I whited out the column names)

![issue](https://github.com/thoughtspot/cs_tools/assets/88211538/c41d86d1-99eb-49c7-a711-a127393991fd)

**Comment by alexwillingham98** [comment] 2023-07-20 22:03
Additionally, this does affect the ability to change/edit perms.

**Comment by boonhapus** [comment] 2023-07-22 18:58
My guess is we're not properly handling the `security/metadata/permissions` call. This might take a bit to debug and this is one of those commands I wanted to rewrite as well.

Are you trying to use Column Level Security here @alexwillingham98 ?

**Comment by alexwillingham98** [comment] 2023-07-22 21:10
Yes, we currently have CLS on our worksheets because we have unencrypted username fields that only 1 or two groups can have access to at the moment.

**Comment by alexwillingham98** [comment] 2023-07-26 16:37
Yes it works fine for most tables, just not the ones with a lot of columns.

**Comment by alexwillingham98** [comment] 2023-08-14 20:08
any update on this issue? I updated to the current cs_tools version and am still seeing this issue

**Comment by boonhapus** [comment] 2023-08-14 22:20
Hey @alexwillingham98 -- sorry, I haven't had much time to look into this one. I can't reproduce this one locally, would you be open to meeting live so I can observe the behavior in your own environment? I'd like to test a few things as well.

I am in UTC-5 / US Central. If you're open to this, please **[send me an email](mailto:nicholas.cooper@thoughtspot.com)** and we'll find a time to look at this.

**Comment by alexwillingham98** [comment] 2023-08-28 14:04
Hey - just tried this out this morning and it seems to be working fine. Thanks!

**Comment by boonhapus** [comment] 2023-09-05 00:18
Closing this as marked fixed in **[v1.4.10](https://github.com/thoughtspot/cs_tools/tree/v1.4.10)** !

**Closed by boonhapus** 2023-09-05 00:18 UTC
Labels: bug
