### ISSUE TITLE
TimeoutError when extracting sharing access metadata

### ISSUE THREAD

**Issue by aldrichsison** [thoughtspot/cs_tools#51] opened 2023-03-14 00:48 UTC
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

Hello!
We're trying to use Searchable to extract sharing / access control metadata.
However, we have observed a long runtime (5 hours) in extracting sharing metadata, which ends up in TimeoutError.
Is there a way to extend or remove limit in read operation to avoid TimeoutError?

Thank you.

**Comment by boonhapus** [comment] 2023-03-14 01:56
5 hours! Roughly how many Users and Groups do you have in ThoughtSpot? What do your timings look like on the status screen - even asking for all the data on my internal cluster, I am seeing total runtime <5 minutes.

![image](https://user-images.githubusercontent.com/14192437/224872014-b793a945-8441-4ffd-b1c7-3b2fa890c69d.png)

I actually have a note about this scenario in the [**Searchable tool**](https://github.com/thoughtspot/cs_tools/blob/a2240d6e2ae2627843027026502d386bf0a4fb80/cs_tools/cli/tools/searchable/app.py#L348-L352). At the very least, I can switch this is key on group, which should take considerably less time.

In a quick test, I've found that it is about 25% more efficient in an internal cluster which is 1000 users strong.

**Comment by aldrichsison** [comment] 2023-03-14 23:29
Hi @boonhapus,
We have roughly 141k users, 5400 groups, and 10300 objects in our Prod cloud cluster.
My latest attempt to finish an extract took 10.5 hours until encountered TimeoutError.

![Screenshot 2023-03-15 042016](https://user-images.githubusercontent.com/74671574/225164126-39561284-99d2-43cf-87cd-680b94bce845.png)

**Comment by boonhapus** [comment] 2023-03-15 02:18
@aldrichsison let me go poke one of the security engineers (who own this API) and see what they come back with. There's some minor tweaks I can make on my end to fetch this data more efficiently... but a timeout at 10hrs of fetching is literally 2 orders of magnitude larger than even the call we make for 140K users, that's confusing. 🤔

I'll get back to with what their thoughts are, and to see if there are _other means of extracting share access permissions from a TS Cloud cluster_? 😉

**Comment by boonhapus** [comment] 2023-03-15 12:22
@aldrichsison , would you be able to share your last 5 log files with me? Engineering would like to take a look at when it occurred to match it to ThoughtSpot's internal reporting stats as well. This will help root cause the drop in performance of the API and should give us a better answer.

```
cs_tools logs report --latest 5
```

You can upload them **[to this secure fileshare](https://thoughtspot.egnyte.com/ul/3KFB6pzgq5)**.

**Comment by boonhapus** [comment] 2023-03-15 12:58
Also finally @aldrichsison - can you take the latest beta update? I've made some changes that should bring that time down as well while engineering investigates the real root cause.

```
cs_tools self update --beta
```

It should be `v1.4.0rc4`.

**Comment by aldrichsison** [comment] 2023-03-15 23:06
Hi @boonhapus ,
I've sent my last 5 logs to you.
I'll also try to extract again under latest beta update. Thank you.

**Comment by aldrichsison** [comment] 2023-03-16 01:53
Well I'll be... 😃 
![Screenshot 2023-03-16 074638](https://user-images.githubusercontent.com/74671574/225489339-12e5d91d-3953-4c44-9156-1ad660338185.png)

**Comment by boonhapus** [comment] 2023-03-16 04:17
This is excellent news @aldrichsison !!

Based on your log files, I think I understand what was happening now as well. We were under extreme memory pressure from having 140K users held in memory during the entire sharing access fetch operation. That causes all the actions to perform far more slowly.

Now that we've solved this issue, I'll go ahead and close this issue. Thanks for reporting it!

**Closed by boonhapus** 2023-03-16 04:17 UTC
Labels: question
